//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceControlUi.SMS_API {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="emrClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class emrClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string docTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sheetverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sheetnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hisdocpkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string histmpxmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sensitiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chartnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patgovidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signcarduseridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signcardusernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endeptidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endeptnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisitSeqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enseqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deletemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string docType {
            get {
                return this.docTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.docTypeField, value) != true)) {
                    this.docTypeField = value;
                    this.RaisePropertyChanged("docType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string isTest {
            get {
                return this.isTestField;
            }
            set {
                if ((object.ReferenceEquals(this.isTestField, value) != true)) {
                    this.isTestField = value;
                    this.RaisePropertyChanged("isTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sheetver {
            get {
                return this.sheetverField;
            }
            set {
                if ((object.ReferenceEquals(this.sheetverField, value) != true)) {
                    this.sheetverField = value;
                    this.RaisePropertyChanged("sheetver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sheetname {
            get {
                return this.sheetnameField;
            }
            set {
                if ((object.ReferenceEquals(this.sheetnameField, value) != true)) {
                    this.sheetnameField = value;
                    this.RaisePropertyChanged("sheetname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string hisdocpk {
            get {
                return this.hisdocpkField;
            }
            set {
                if ((object.ReferenceEquals(this.hisdocpkField, value) != true)) {
                    this.hisdocpkField = value;
                    this.RaisePropertyChanged("hisdocpk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string histmpxml {
            get {
                return this.histmpxmlField;
            }
            set {
                if ((object.ReferenceEquals(this.histmpxmlField, value) != true)) {
                    this.histmpxmlField = value;
                    this.RaisePropertyChanged("histmpxml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sensitive {
            get {
                return this.sensitiveField;
            }
            set {
                if ((object.ReferenceEquals(this.sensitiveField, value) != true)) {
                    this.sensitiveField = value;
                    this.RaisePropertyChanged("sensitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string chartno {
            get {
                return this.chartnoField;
            }
            set {
                if ((object.ReferenceEquals(this.chartnoField, value) != true)) {
                    this.chartnoField = value;
                    this.RaisePropertyChanged("chartno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string patgovid {
            get {
                return this.patgovidField;
            }
            set {
                if ((object.ReferenceEquals(this.patgovidField, value) != true)) {
                    this.patgovidField = value;
                    this.RaisePropertyChanged("patgovid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string patname {
            get {
                return this.patnameField;
            }
            set {
                if ((object.ReferenceEquals(this.patnameField, value) != true)) {
                    this.patnameField = value;
                    this.RaisePropertyChanged("patname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string signcarduserid {
            get {
                return this.signcarduseridField;
            }
            set {
                if ((object.ReferenceEquals(this.signcarduseridField, value) != true)) {
                    this.signcarduseridField = value;
                    this.RaisePropertyChanged("signcarduserid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string signcardusername {
            get {
                return this.signcardusernameField;
            }
            set {
                if ((object.ReferenceEquals(this.signcardusernameField, value) != true)) {
                    this.signcardusernameField = value;
                    this.RaisePropertyChanged("signcardusername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string endeptid {
            get {
                return this.endeptidField;
            }
            set {
                if ((object.ReferenceEquals(this.endeptidField, value) != true)) {
                    this.endeptidField = value;
                    this.RaisePropertyChanged("endeptid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string endeptname {
            get {
                return this.endeptnameField;
            }
            set {
                if ((object.ReferenceEquals(this.endeptnameField, value) != true)) {
                    this.endeptnameField = value;
                    this.RaisePropertyChanged("endeptname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string entime {
            get {
                return this.entimeField;
            }
            set {
                if ((object.ReferenceEquals(this.entimeField, value) != true)) {
                    this.entimeField = value;
                    this.RaisePropertyChanged("entime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string VisitSeq {
            get {
                return this.VisitSeqField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitSeqField, value) != true)) {
                    this.VisitSeqField = value;
                    this.RaisePropertyChanged("VisitSeq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string enseq {
            get {
                return this.enseqField;
            }
            set {
                if ((object.ReferenceEquals(this.enseqField, value) != true)) {
                    this.enseqField = value;
                    this.RaisePropertyChanged("enseq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string signstatus {
            get {
                return this.signstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.signstatusField, value) != true)) {
                    this.signstatusField = value;
                    this.RaisePropertyChanged("signstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string deletemark {
            get {
                return this.deletemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.deletemarkField, value) != true)) {
                    this.deletemarkField = value;
                    this.RaisePropertyChanged("deletemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                if ((object.ReferenceEquals(this.sexField, value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Identity {
            get {
                return this.IdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityField, value) != true)) {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMailClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SendMailClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReciverAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCAddrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderAccount {
            get {
                return this.SenderAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAccountField, value) != true)) {
                    this.SenderAccountField = value;
                    this.RaisePropertyChanged("SenderAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderPassword {
            get {
                return this.SenderPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderPasswordField, value) != true)) {
                    this.SenderPasswordField = value;
                    this.RaisePropertyChanged("SenderPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciverAddr {
            get {
                return this.ReciverAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.ReciverAddrField, value) != true)) {
                    this.ReciverAddrField = value;
                    this.RaisePropertyChanged("ReciverAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MailServer {
            get {
                return this.MailServerField;
            }
            set {
                if ((object.ReferenceEquals(this.MailServerField, value) != true)) {
                    this.MailServerField = value;
                    this.RaisePropertyChanged("MailServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CCAddr {
            get {
                return this.CCAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.CCAddrField, value) != true)) {
                    this.CCAddrField = value;
                    this.RaisePropertyChanged("CCAddr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SendSMSClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string full_phsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_unitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string system_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string send_text {
            get {
                return this.send_textField;
            }
            set {
                if ((object.ReferenceEquals(this.send_textField, value) != true)) {
                    this.send_textField = value;
                    this.RaisePropertyChanged("send_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phs {
            get {
                return this.phsField;
            }
            set {
                if ((object.ReferenceEquals(this.phsField, value) != true)) {
                    this.phsField = value;
                    this.RaisePropertyChanged("phs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string full_phs {
            get {
                return this.full_phsField;
            }
            set {
                if ((object.ReferenceEquals(this.full_phsField, value) != true)) {
                    this.full_phsField = value;
                    this.RaisePropertyChanged("full_phs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string send_unit {
            get {
                return this.send_unitField;
            }
            set {
                if ((object.ReferenceEquals(this.send_unitField, value) != true)) {
                    this.send_unitField = value;
                    this.RaisePropertyChanged("send_unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string system_name {
            get {
                return this.system_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.system_nameField, value) != true)) {
                    this.system_nameField = value;
                    this.RaisePropertyChanged("system_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS_API.EricWebServicesSoap")]
    public interface EricWebServicesSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  myClass 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoTempEMR", ReplyAction="*")]
        ServiceControlUi.SMS_API.InsertIntoTempEMRResponse InsertIntoTempEMR(ServiceControlUi.SMS_API.InsertIntoTempEMRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoTempEMR", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControlUi.SMS_API.InsertIntoTempEMRResponse> InsertIntoTempEMRAsync(ServiceControlUi.SMS_API.InsertIntoTempEMRRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  myClass 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        ServiceControlUi.SMS_API.SendMailResponse SendMail(ServiceControlUi.SMS_API.SendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControlUi.SMS_API.SendMailResponse> SendMailAsync(ServiceControlUi.SMS_API.SendMailRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  myClass 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        ServiceControlUi.SMS_API.SendSMSResponse SendSMS(ServiceControlUi.SMS_API.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControlUi.SMS_API.SendSMSResponse> SendSMSAsync(ServiceControlUi.SMS_API.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoTempEMRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoTempEMR", Namespace="http://tempuri.org/", Order=0)]
        public ServiceControlUi.SMS_API.InsertIntoTempEMRRequestBody Body;
        
        public InsertIntoTempEMRRequest() {
        }
        
        public InsertIntoTempEMRRequest(ServiceControlUi.SMS_API.InsertIntoTempEMRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoTempEMRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceControlUi.SMS_API.emrClass myClass;
        
        public InsertIntoTempEMRRequestBody() {
        }
        
        public InsertIntoTempEMRRequestBody(ServiceControlUi.SMS_API.emrClass myClass) {
            this.myClass = myClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoTempEMRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoTempEMRResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceControlUi.SMS_API.InsertIntoTempEMRResponseBody Body;
        
        public InsertIntoTempEMRResponse() {
        }
        
        public InsertIntoTempEMRResponse(ServiceControlUi.SMS_API.InsertIntoTempEMRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoTempEMRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertIntoTempEMRResult;
        
        public InsertIntoTempEMRResponseBody() {
        }
        
        public InsertIntoTempEMRResponseBody(string InsertIntoTempEMRResult) {
            this.InsertIntoTempEMRResult = InsertIntoTempEMRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMail", Namespace="http://tempuri.org/", Order=0)]
        public ServiceControlUi.SMS_API.SendMailRequestBody Body;
        
        public SendMailRequest() {
        }
        
        public SendMailRequest(ServiceControlUi.SMS_API.SendMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceControlUi.SMS_API.SendMailClass myClass;
        
        public SendMailRequestBody() {
        }
        
        public SendMailRequestBody(ServiceControlUi.SMS_API.SendMailClass myClass) {
            this.myClass = myClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceControlUi.SMS_API.SendMailResponseBody Body;
        
        public SendMailResponse() {
        }
        
        public SendMailResponse(ServiceControlUi.SMS_API.SendMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMailResult;
        
        public SendMailResponseBody() {
        }
        
        public SendMailResponseBody(string SendMailResult) {
            this.SendMailResult = SendMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public ServiceControlUi.SMS_API.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(ServiceControlUi.SMS_API.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceControlUi.SMS_API.SendSMSClass myClass;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(ServiceControlUi.SMS_API.SendSMSClass myClass) {
            this.myClass = myClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceControlUi.SMS_API.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(ServiceControlUi.SMS_API.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EricWebServicesSoapChannel : ServiceControlUi.SMS_API.EricWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EricWebServicesSoapClient : System.ServiceModel.ClientBase<ServiceControlUi.SMS_API.EricWebServicesSoap>, ServiceControlUi.SMS_API.EricWebServicesSoap {
        
        public EricWebServicesSoapClient() {
        }
        
        public EricWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EricWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EricWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EricWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControlUi.SMS_API.InsertIntoTempEMRResponse ServiceControlUi.SMS_API.EricWebServicesSoap.InsertIntoTempEMR(ServiceControlUi.SMS_API.InsertIntoTempEMRRequest request) {
            return base.Channel.InsertIntoTempEMR(request);
        }
        
        public string InsertIntoTempEMR(ServiceControlUi.SMS_API.emrClass myClass) {
            ServiceControlUi.SMS_API.InsertIntoTempEMRRequest inValue = new ServiceControlUi.SMS_API.InsertIntoTempEMRRequest();
            inValue.Body = new ServiceControlUi.SMS_API.InsertIntoTempEMRRequestBody();
            inValue.Body.myClass = myClass;
            ServiceControlUi.SMS_API.InsertIntoTempEMRResponse retVal = ((ServiceControlUi.SMS_API.EricWebServicesSoap)(this)).InsertIntoTempEMR(inValue);
            return retVal.Body.InsertIntoTempEMRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControlUi.SMS_API.InsertIntoTempEMRResponse> ServiceControlUi.SMS_API.EricWebServicesSoap.InsertIntoTempEMRAsync(ServiceControlUi.SMS_API.InsertIntoTempEMRRequest request) {
            return base.Channel.InsertIntoTempEMRAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControlUi.SMS_API.InsertIntoTempEMRResponse> InsertIntoTempEMRAsync(ServiceControlUi.SMS_API.emrClass myClass) {
            ServiceControlUi.SMS_API.InsertIntoTempEMRRequest inValue = new ServiceControlUi.SMS_API.InsertIntoTempEMRRequest();
            inValue.Body = new ServiceControlUi.SMS_API.InsertIntoTempEMRRequestBody();
            inValue.Body.myClass = myClass;
            return ((ServiceControlUi.SMS_API.EricWebServicesSoap)(this)).InsertIntoTempEMRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControlUi.SMS_API.SendMailResponse ServiceControlUi.SMS_API.EricWebServicesSoap.SendMail(ServiceControlUi.SMS_API.SendMailRequest request) {
            return base.Channel.SendMail(request);
        }
        
        public string SendMail(ServiceControlUi.SMS_API.SendMailClass myClass) {
            ServiceControlUi.SMS_API.SendMailRequest inValue = new ServiceControlUi.SMS_API.SendMailRequest();
            inValue.Body = new ServiceControlUi.SMS_API.SendMailRequestBody();
            inValue.Body.myClass = myClass;
            ServiceControlUi.SMS_API.SendMailResponse retVal = ((ServiceControlUi.SMS_API.EricWebServicesSoap)(this)).SendMail(inValue);
            return retVal.Body.SendMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControlUi.SMS_API.SendMailResponse> ServiceControlUi.SMS_API.EricWebServicesSoap.SendMailAsync(ServiceControlUi.SMS_API.SendMailRequest request) {
            return base.Channel.SendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControlUi.SMS_API.SendMailResponse> SendMailAsync(ServiceControlUi.SMS_API.SendMailClass myClass) {
            ServiceControlUi.SMS_API.SendMailRequest inValue = new ServiceControlUi.SMS_API.SendMailRequest();
            inValue.Body = new ServiceControlUi.SMS_API.SendMailRequestBody();
            inValue.Body.myClass = myClass;
            return ((ServiceControlUi.SMS_API.EricWebServicesSoap)(this)).SendMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControlUi.SMS_API.SendSMSResponse ServiceControlUi.SMS_API.EricWebServicesSoap.SendSMS(ServiceControlUi.SMS_API.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(ServiceControlUi.SMS_API.SendSMSClass myClass) {
            ServiceControlUi.SMS_API.SendSMSRequest inValue = new ServiceControlUi.SMS_API.SendSMSRequest();
            inValue.Body = new ServiceControlUi.SMS_API.SendSMSRequestBody();
            inValue.Body.myClass = myClass;
            ServiceControlUi.SMS_API.SendSMSResponse retVal = ((ServiceControlUi.SMS_API.EricWebServicesSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControlUi.SMS_API.SendSMSResponse> ServiceControlUi.SMS_API.EricWebServicesSoap.SendSMSAsync(ServiceControlUi.SMS_API.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControlUi.SMS_API.SendSMSResponse> SendSMSAsync(ServiceControlUi.SMS_API.SendSMSClass myClass) {
            ServiceControlUi.SMS_API.SendSMSRequest inValue = new ServiceControlUi.SMS_API.SendSMSRequest();
            inValue.Body = new ServiceControlUi.SMS_API.SendSMSRequestBody();
            inValue.Body.myClass = myClass;
            return ((ServiceControlUi.SMS_API.EricWebServicesSoap)(this)).SendSMSAsync(inValue);
        }
    }
}
